### ISSUE TITLE
readSLCF3Ddata 

### ISSUE THREAD

**Issue by KeepKeepUp** [johodges/pyfdstools#1]
Hello, after looking at your fds tools, I am interested in readSLCF3Ddata function in extraplot3Ddata.py file, because I want to parse the sliced files after fds simulation. Just like *_1_*.sf .   I originally looked at the py script language in fds, but I don't understand two variables in it. I sent a issues to the developers, but one of them replied that he did not know, and recommended the address of the parsed data to you, because I do not know much about sliced files and asked for your advice.I'd like to know your understanding of parsing slcf data using a scripting language, such as the parsing process.How to parse the data has puzzled me for a long time.I am looking forward to your reply.thanks!

**Comment by johodges** [comment]
Thanks for reaching out. Could you clarify a bit what your question is? The binary encoding of the slice files used in FDS is documented in the FDS User Guide. I used that information to create the python package to parse the files.

**Comment by KeepKeepUp** [comment]
I saw relevant information in 25.9 of the FDS User Guide, and I don't know if it was you who said it. I set three Quantities in the  FDS script file. The.sf file, which was generated after compiling using the cmd window of fds, contained information about the slice data, and I wanted to parse out the data related to the time average several times. The slice area I set up is 3D, I used the built-in program（fds2ascii）parsing, but I found that if there were too many grids, fds2ascii could not be used multiple times to parse the data (about the time average).

**Comment by johodges** [comment]
Could you attach your fds input file and the script which is causing the issue?

**Comment by KeepKeepUp** [comment]
Thanks your reply! I find a problem,when i use the fds2ascii to  parse the  .sf file ,the 3d cannot to get ,but the 2d can get. my fds input file as follow.Look forward to your help.Thank you again！
[leak.txt](https://github.com/johodges/pyfdstools/files/11412740/leak.txt)

**Comment by johodges** [comment]
If there is an issue with fds2acii you will need to ask about that on the FDS group. Are you having an issue with pyfdstools importing your data?
