### ISSUE TITLE
Error when reading 2D slice files

### ISSUE THREAD

**Issue by FG123456** [johodges/pyfdstools#4]
Hi, 

I am having a bit of trouble plotting 2d slice files when I introduce a slightly more complex FDS case than what is in the example case.

I have attached the FDS file - it is essentially the exact same as the original couch case (slice files are in the same location) although it is slightly extended and introduces multiple meshes. 

The python script is nearly identical to your example with the aspects that aren't related to 2d slice files being removed. The file is attached. 

This reduced script still works with the original FDS example. However, when attempting it with the new case I receive two errors - one appears to involve the MULT_ID function and the other is 'UnboundLocalError: local variable 'key' referenced before assignment'. 

I have been attempting to brute force testing each line due to a lack of python knowledge - this as you might imagine hasn't been successful. 

Any ideas on how to get this to run so that I may be able to produce a plot? 

Thanks for the help
 

[FG_SLICEFILE.txt](https://github.com/johodges/pyfdstools/files/11268333/FG_SLICEFILE.txt)
[case001.txt](https://github.com/johodg
![Error Message](https://user-images.githubusercontent.com/131226659/232961945-0f4e620c-af0a-4b80-a5ed-a13a6156b7de.PNG)
es/pyfdstools/files/11268325/case001.txt)

**Comment by FG123456** [comment]
Please ignore…daft mistake

**Comment by johodges** [comment]
No problem, let me know if you run into further issues. I just pushed a new version to pypi which has a lot of fixes on importing the (.fds) file itself.
