### ISSUE TITLE
Problems about `iX,eX,iY,eY,iZ,eZ` in `readSLCFheader()`

### ISSUE THREAD

**Issue by LextU** [johodges/pyfdstools#5]
[test_1_1.txt](https://github.com/johodges/pyfdstools/files/11912965/test_1_1.txt)
Hi, thank you very much for developing such a powerful tool! I met some problem doing postprocessing of FDS simulation in large scale scenarios with `pyfdstools`.

In `readSLCFheader()` in file `extractPlot3Ddata.py`, 115th~139th bytes are unpacked to obtain  `iX,eX,iY,eY,iZ,eZ` and it worked well before. However, I recently simulated a scenario with large scale and some Z-direction slices (`SLCF PBZ=xx...`) spanned more than 200 grids, and the header of `SLCF` in `.sf` file is recorded in a strange way and `size = struct.unpack('>iiiiii', data[115:139])` no longer works. 

For example, I got a SLCF that spanned 290 grids in the x-direction, and it's information is recorded in `.smv` file like:

```
SLCF     5 # STRUCTURED &     0   290     0    60    60    60 !     38      0
 turbine_2_5_74.sf
 METHANE DENSITY
 rho_CH4
 kg/m3
```

then I checked `.sf` file (`turbine_1_4.sf` here) and found that 115th~139th bytes are: 

```
HEX:
00 00 00 00   00 00 00 22  # iX, eX
01 00 00 00   00 00 00 3c  # iY, eY
00 00 00 3c   00 00 00 3c  # iZ, eZ
```

which means `iX,eX,iY,eY,iZ,eZ = 0, 34, 16777216, 60, 60, 60`, which is the same result as `iX,eX,iY,eY,iZ,eZ = struct.unpack('>iiiiii', data[115:139])`. `iX` (0x00000022) and `iY` (0x01000000) here are really strange.

I checked FDS source code of SLCF header output control: 
```
OPEN(LU_SLCF(N,NM),    FILE=FN_SLCF(N,NM),   FORM='UNFORMATTED',    STATUS='REPLACE')
WRITE(LU_SLCF(N,NM))     SL%I1,SL%I2,SL%J1,SL%J2,SL%K1,SL%K2
```
it seems that only six integer are written to `.sf` file and nothing is strange? I can't find the reason and need your help, thanks! 

#### Appendix:
0. A `test_1_1.sf` file is attached, see no.2 below.
1. FDS version: 6.7.9
2. Another slice named `test_1_1.sf` with `iX, eX, iY, eY, iZ, eZ = 0, 515, 0, 300, 25, 25` is tested and `.sf` file shows that these values are (0, 3, 33554432, 44, 16777221, 5) with `HEX: 00 00 00 00, 00 00 00 03, 02 00 00 00, 00 00 00 2c, 01 00 00 05, 00 00 00 05` as 115th~139th bytes. It seems that `eX=515` here exceeded some 'threshold' and caused wrong value together with its neighbour `iY`, and `eY=300` also effected its neighbour `iZ` ?
3. Another slice with `iX, eX, iY, eY, iZ, eZ = 0, 116, 0, 24, 12, 12` is tested and everything is ok. Maybe the 'threshold' is 127 ?
4. BTW, I thought `I1, I2, ..., K2` should be placed in 91th-114th bytes in `.sf` file according to next codes (lines 1039~1058 of `dump.f90`) and obviously I'm wrong. But I don't know why, could you please guide me? 
```
OPEN(LU_SLCF(N,NM),             FILE=FN_SLCF(N,NM),               FORM='UNFORMATTED',STATUS='REPLACE')
WRITE(LU_SLCF(N,NM)) SL%SMOKEVIEW_LABEL(1:30)
WRITE(LU_SLCF(N,NM)) SL%SMOKEVIEW_BAR_LABEL(1:30)
WRITE(LU_SLCF(N,NM)) OUTPUT_QUANTITY(SL%INDEX)%UNITS(1:30)
IF (.NOT.SL%TERRAIN_SLICE) THEN
         WRITE(LU_SLCF(N,NM))              SL%I1,SL%I2,SL%J1,SL%J2,SL%K1,SL%K2
```

Thank you again for developing `pyfdstools`!

**Comment by LextU** [comment]
I configured unpack method from `size = struct.unpack('>iiiiii', data[115:139])` to `size = struct.unpack('<iiiiii', data[118:142])` and got correct result on both `turbine_1_4.sf` and `test_1_1.sf` above, and some other tests. But I haven't found the reason.

**Comment by johodges** [comment]
Thanks for posting. I'll take a look at your test case and comment back what I find.

**Comment by johodges** [comment]
Could you post the FDS file which outputs the slice file?

**Comment by LextU** [comment]
Of course but I'm afraid the scenario of those FDS files are tooooo large to run. I created a tiny FDS file that will trigger the same problem:
```
&HEAD CHID='test'/
&WIND SPEED=2.485, DIRECTION=180.0/
&TIME T_END=10/
&MESH ID='Mesh01', IJK=300,10,10, XB=0,300,0,10,0,10/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBZ=5.0/
&TAIL /
```
This will create a slice that spans 300 grids in X-direction, and result of `struct.unpack('>iiiiii', data[115:139])` is `(0, 44, 16777216, 10, 5, 5)` instead of `(0, 300, 0, 10, 5, 5)`.

It seems that FORTRAN outputs 4 bytes both before and after each execution of `write()`, so I think the 118th byte should be first byte recording `I1, I2, J1, .., K2` instead of 115th one. But I havn't figure out why it is written in little-endian format.

**Comment by johodges** [comment]
Thanks for posting. Little endian is a more common data format for operating systems than big endian these days. However, when I originally made this library FDS was storing out these files as big endian. This is the first time I've run into a conflict with the endianness. I am working on editing the routines to explicitly check for endianness of the machine that ran the simulation and the machine that is reading the data. I should have it fixed sometime this week.

**Comment by johodges** [comment]
This should be fixed in the latest source. The header bytes needed to be shifted right by 4 as noted in this issue. This previously had not been flagged as an issue because a big endian representation shifted by 4 bytes resulted in the same number as long as the number of cells in any direction was < 256. Here is the script I used to test your output. Let me know if this works on your other case and we will close out this issue.

import pyfdstools as fds
import os
from collections import defaultdict
import numpy as np
import matplotlib.pyplot as plt

if __name__ == '__main__':
    (chid, resultDir) = ('test', os.path.abspath(".") + os.sep)
    
    (qty, unit) = ('VELOCITY', 'm/s')
    (tStart, tEnd) = (0, 10)
    (axis, value) = (3, 5)
    (qnty_mn, qnty_mx) = (2.45, 2.5)
    
    datas = defaultdict(bool)
    grid, data, times = fds.readSLCF2Ddata(chid, resultDir, qty)
    tStartInd = np.argwhere(times >= tStart)[0][0]
    tEndInd = np.argwhere(times <= tEnd)[-1][0]
    data_tavg = np.nanmean(data[:, :, :, tStartInd:tEndInd], axis=3)
    datas[qty] = data_tavg.copy()
    datas['GRID'] = grid
    datas['TIMES'] = times
    
    x, z, data_slc = fds.findSliceLocation(datas['GRID'], datas[qty], axis, value)
    fig = fds.plotSlice(x, z, data_slc, axis,
                        qnty_mn=qnty_mn, qnty_mx=qnty_mx,
                        clabel="%s (%s)"%(qty, unit),
                        cbarticks=[2.45,2.46,2.47,2.48,2.49,2.50])
    plt.savefig('out.png', dpi=300)

**Comment by LextU** [comment]
Yes it works well! I noticed `endianness` is determined in a robust way by `getEndianness()`, that's cool.

My problems are all solved, thank you for your time! And I really learned a lot from your code, this project is really amazing tools for FDS users, thank you!
